# Rの基礎
Rの基本的な言語仕様をまとめています．
ある程度他の言語を触ったことがある人向けの内容です.
「Rだとあれの書き方どうやるの？」というリファレンスにどうぞ．

## 使い方
「Shift + Enter」でセルを実行し，プログラムの内容とその実行結果を確認しましょう.

---

# 変数と演算

In [3]:
# 変数に代入
x<-10
y<-3
# 演算
x+y #和
x-y #差
x*y #積
x/y #商
x^y #累乗 x**yでもOK
x%/%y#整数商
x%%y #剰余

[1] 13

[1] 7

[1] 30

[1] 3.333333

[1] 1000

[1] 3

[1] 1

---
# データ型
Rの型はもっと細かいですがここでは大雑把に紹介します.  
詳しいことは以下をチェック．

[\[参考URL\] R の「型」について](http://www.hnagata.net/archives/479)

## 実数

In [2]:
a<-100
mode(a)
typeof(a)

[1] "numeric"

[1] "double"

## 複素数

In [4]:
a<-1+2i #複素数
mode(a)
typeof(a)
Re(a) #実部
Im(a) #虚部
abs(a) #絶対値
Arg(a) #偏角
Conj(a) #共役複素数

[1] "complex"

[1] "complex"

[1] 1

[1] 2

[1] 2.236068

[1] 1.107149

[1] 1-2i

## 文字列

In [5]:
a<-"テスト" #文字列
mode(a)
typeof(a)

[1] "character"

[1] "character"

## 真偽値

In [6]:
a<-TRUE
mode(a)
typeof(a)
#TRUE, FALSEは省略可
b<-T
c<-F
b
c

[1] "logical"

[1] "logical"

[1] TRUE

[1] FALSE

## 型判定

In [7]:
is.numeric(1)
is.complex(1+1i)
is.character("あああ")
is.logical(FALSE)

[1] TRUE

[1] TRUE

[1] TRUE

[1] TRUE

## 型変換

In [ ]:
x<-10
is.character(x)
is.character(as.character(x)) #as.xxxxで変換

---
# ベクトル

ベクトルは複数の要素を格納しておくためのオブジェクトのうちのひとつです．
ベクトルは他言語で言うところの1次元配列のような使い方ができます．  
配列と違って，ベクトルは多次元的なデータは扱いません．Rには配列型もあるので，多次元的なデータを保持しておく場合は配列型を使うと良いでしょう．
以下のURLが参考になります．


[\[参考URL\] ベクトル、行列、データフレーム、リスト、配列、テーブルの違い
](https://cell-innovation.nig.ac.jp/surfers/vector_difference.html)

## ベクトルの作成

In [ ]:
a<-c(1,2,1,3)
b<-c(1,2,2,4)
#表示
a
b

## 規則性のあるベクトル
### 差が1の数列

In [8]:
0:10
3:-3

[1]  0  1  2  3  4  5  6  7  8  9 10

[1]  3  2  1  0 -1 -2 -3

### 繰り返し（rep）

In [3]:
rep(11,3) #rep(繰り返す対象, 回数)
rep(c(1,2,3),times=8) #1,2,3を8回繰り返す．
rep(c(1,2,3),length=8) #1,2,3を長さ8になるまで繰り返す．
rep(c(1,2,3),each=3) #それぞれ3回繰り返す．
rep(c(1,2,3),each=3,length=8) #組み合わせ

[1] 11 11 11

[1] 1 2 3 1 2 3 1 2 3 1 2 3 1 2 3 1 2 3 1 2 3 1 2 3

[1] 1 2 3 1 2 3 1 2

[1] 1 1 1 2 2 2 3 3 3

[1] 1 1 1 2 2 2 3 3

### 数列（seq）

In [4]:
seq(0,10,length=5) #0から10まで5等分する等差数列
seq(0,11,by=2) #0から11まで2ずつ増加する等差数列

[1]  0.0  2.5  5.0  7.5 10.0

[1]  0  2  4  6  8 10

### 重複した値の削除

In [6]:
unique(c(1,2,1,3,4,5,1,6))

[1] 1 2 3 4 5 6

## ベクトル要素の取得

In [36]:
a<-c('A', 'B', 'C', 'D', 'E', 'F')
a[2]
a[-2]

#インデックスをベクトルで指定する対応する値をまとめて取得できる．
a[c(5,2,3)]
a[1:3]
a[-1:-3]

[1] "B"

[1] "A" "C" "D" "E" "F"

[1] "E" "B" "C"

[1] "A" "B" "C"

[1] "D" "E" "F"

## ベクトルの計算

In [7]:
a<-c(1,2,1,3)
b<-c(1,2,2,4)
a+b #和
a-b #差
a*b #積
a/b #商

[1] 2 4 3 7

[1]  0  0 -1 -1

[1]  1  4  2 12

[1] 1.00 1.00 0.50 0.75

## ベクトルの便利メソッド
### 結合

In [17]:
a<-c(1,2,3)
b<-c(4,5,6)
c<-c(7,8,9)
c(a,b,c)

[1] 1 2 3 4 5 6 7 8 9

### 挿入

In [22]:
a<-1:9
b<-c(0,-1,-2)
append(a, b, after=0)
append(a, b, after=1)

[1]  0 -1 -2  1  2  3  4  5  6  7  8  9

[1]  1  0 -1 -2  2  3  4  5  6  7  8  9

### 置換

In [45]:
a<-1:9
replace(a, c(2,5,6), 10) #2,5,6番目を10に置換する．
replace(a, which(a>5), 10) #5以上の要素を10に置換する．

#オマケ
which(c(8,9,3,9)!=9) #whichは条件に一致した要素のインデックスをベクトル形式で返す．

[1]  1 10  3  4 10 10  7  8  9

[1]  1  2  3  4  5 10 10 10 10

[1] 1 3

### ベクトルの要素数の取得

In [78]:
a<-0:4
length(a)

[1] 5

### ベクトルの並べ替え

In [34]:
x<-c(53,32,29,81,29,10,47)
sort(x) #昇順
sort(x,decreasing=TRUE) #降順
order(x) #orderはxをソートするためのインデックスをベクトル型で返す．
x[order(x)] #orderを使って参照すると並び替え済みのベクトルが得られる．

[1] 10 29 29 32 47 53 81

[1] 81 53 47 32 29 29 10

[1] 6 3 5 2 7 1 4

[1] 10 29 29 32 47 53 81

---
# 行列
2次元的にデータを保持するためのオブジェクトです．
行列を使うことで行列計算に使う便利な関数を利用することができます．

## 行列の作成

In [53]:
 matrix(1:12, nrow=4, ncol=3)  #nrowが行，ncolが列
 matrix(1:12, nrow=4, ncol=3, byrow=T)  #列方向から先に埋めたいときはbyrow=T

[,1] [,2] [,3]
[1,] 1    5     9  
[2,] 2    6    10  
[3,] 3    7    11  
[4,] 4    8    12

[,1] [,2] [,3]
[1,]  1    2    3  
[2,]  4    5    6  
[3,]  7    8    9  
[4,] 10   11   12

## 行列要素の取得

In [102]:
a<-matrix(1:9,nrow=3,ncol=3,byrow=T)
a #行列の中身[[1,2,3], [4,5,6], [7,8,9]]
a[1,2] #1行2列目の要素を取得 [2]
a[1:3,1:2] #1〜3行目，および1〜2列目の範囲を取得 [[1,2], [4,5], [7,8]]
a[-2,-1] #2行目または1列目でない範囲を取得 [[2,3], [8,9]]
a[-1:-2,-2:-3] #1〜2行目および2〜3列目でない範囲を取得 [7]
which(a>3, arr.ind=TRUE) #3以上の要素のインデックスを取得 (2行目の1列目etc...)
a[a>3] #3以上の要素を取得 [4,5,6,7,8,9]
a[a>3]<-0 #3以上の要素に0を代入
a #[[1,2,3], [0,0,0], [0,0,0]]

[,1] [,2] [,3]
[1,] 1    2    3   
[2,] 4    5    6   
[3,] 7    8    9

[1] 2

[,1] [,2]
[1,] 1    2   
[2,] 4    5   
[3,] 7    8

[,1] [,2]
[1,] 2    3   
[2,] 8    9

[1] 7

row col
[1,] 2   1  
[2,] 3   1  
[3,] 2   2  
[4,] 3   2  
[5,] 2   3  
[6,] 3   3

[1] 4 7 5 8 6 9

[,1] [,2] [,3]
[1,] 1    2    3   
[2,] 0    0    0   
[3,] 0    0    0

## 行列の計算

In [112]:
a<-matrix(1:9,nrow=3,ncol=3)
b<-matrix(1:9,nrow=3,ncol=3)
a
10*a #各要素を10倍にする．
a*b #各要素の積を計算する．a[ i, j ]*b[ i, j ]を計算している．行列の積ではないので注意．
a%*%b #行列の積はこちら．Σa[ i, j ]*b[ j, i ]を計算している．
a+b #行列の和
a-b #行列の差

[,1] [,2] [,3]
[1,] 1    4    7   
[2,] 2    5    8   
[3,] 3    6    9

[,1] [,2] [,3]
[1,] 10   40   70  
[2,] 20   50   80  
[3,] 30   60   90

[,1] [,2] [,3]
[1,] 1    16   49  
[2,] 4    25   64  
[3,] 9    36   81

[,1] [,2] [,3]
[1,] 30   66   102 
[2,] 36   81   126 
[3,] 42   96   150

[,1] [,2] [,3]
[1,] 2     8   14  
[2,] 4    10   16  
[3,] 6    12   18

[,1] [,2] [,3]
[1,] 0    0    0   
[2,] 0    0    0   
[3,] 0    0    0

## 行列の大きさ

In [89]:
a<-matrix(1:6,nrow=2,ncol=3,byrow=T)
a
dim(a) #（行数, 列数）
nrow(a) #行数
ncol(a) #列数
length(a) #要素数

[,1] [,2] [,3]
[1,] 1    2    3   
[2,] 4    5    6

[1] 2 3

[1] 2

[1] 3

[1] 6

## 行列の合計とか平均とか

In [85]:
a<-matrix(1:9,nrow=3, ncol=3,byrow=T)
a
rowSums(a) #行の合計 [6,15,24]
colSums(a) #列の合計 [12,15,18]
rowMeans(a) #行の平均 [2,5,8]
colMeans(a) #列の平均 [4,5,6]
sum(a) #全要素の合計 [45]
mean(a) #全要素の平均 [5]

[,1] [,2] [,3]
[1,] 1    2    3   
[2,] 4    5    6   
[3,] 7    8    9

[1]  6 15 24

[1] 12 15 18

[1] 2 5 8

[1] 4 5 6

[1] 45

[1] 5

## 行列の転置

In [114]:
a<-matrix(1:9,nrow=3, ncol=3,byrow=T)
a
t(a)

[,1] [,2] [,3]
[1,] 1    2    3   
[2,] 4    5    6   
[3,] 7    8    9

[,1] [,2] [,3]
[1,] 1    4    7   
[2,] 2    5    8   
[3,] 3    6    9

## 逆行列の計算

In [129]:
a<-matrix(c(1,1,-1,-2,0,1,0,2,1),nrow=3, ncol=3)
a #もとの行列の表示
solve(a) #逆行列の表示
a%*%solve(a) #もとの行列と逆行列の積をとると単位行列になることが確認できる．

[,1] [,2] [,3]
[1,]  1   -2   0   
[2,]  1    0   2   
[3,] -1    1   1

[,1]  [,2] [,3]
[1,] -0.50 0.50 -1.0
[2,] -0.75 0.25 -0.5
[3,]  0.25 0.25  0.5

[,1] [,2] [,3]
[1,] 1    0    0   
[2,] 0    1    0   
[3,] 0    0    1

## 単位行列

In [131]:
diag(3) #3x3の単位行列

[,1] [,2] [,3]
[1,] 1    0    0   
[2,] 0    1    0   
[3,] 0    0    1

## 対角行列

In [134]:
diag(c(1,3,3))
diag(1:3)

[,1] [,2] [,3]
[1,] 1    0    0   
[2,] 0    3    0   
[3,] 0    0    3

[,1] [,2] [,3]
[1,] 1    0    0   
[2,] 0    2    0   
[3,] 0    0    3

## 行列の内積 

In [153]:
a<-matrix(1:6,nrow=2, ncol=2)
b<-c(1,2)
a
b
crossprod(a,b)

[,1] [,2]
[1,] 1    3   
[2,] 2    4

[1] 1 2

[,1]
[1,]  5  
[2,] 11

## 固有値と固有ベクトル

In [193]:
a<-matrix(c(4,2,1,3),nrow=2, ncol=2)
a
b<-eigen(a)
b
b$values
b$vectors

[,1] [,2]
[1,] 4    1   
[2,] 2    3

eigen() decomposition
$values
[1] 5 2

$vectors
          [,1]       [,2]
[1,] 0.7071068 -0.4472136
[2,] 0.7071068  0.8944272


[1] 5 2

[,1]      [,2]      
[1,] 0.7071068 -0.4472136
[2,] 0.7071068  0.8944272

## 行列式

In [149]:
a<-matrix(c(1,2,3,4),nrow=2, ncol=2)
a
det(a)

[,1] [,2]
[1,] 1    3   
[2,] 2    4

[1] -2

---
# データフレーム
データフレームは行列と同じく2次元配置のデータを扱います．
ベクトルや行列とは異なり，データフレームは違う種類の要素（数値，文字列，真偽値など）をまとめることができます．  

## データフレームの作成

In [57]:
df<-data.frame(
  subject=c("A", "B", "C", "D"),
  result=c(T, T, F, T)
)
df

subject result
1 A        TRUE 
2 B        TRUE 
3 C       FALSE 
4 D        TRUE

## データフレーム要素の参照

In [56]:
df<-data.frame(
  subject=c("A", "B", "C", "D"),
  result=c(T, T, F, T)
)
df
df$subject #ヘッダ名で参照
df[2,1] #2行1列目を参照
df[,1] #1列目を参照
df[2,] #2行目を参照
df[1:3,] #1～3行目を参照

subject result
1 A        TRUE 
2 B        TRUE 
3 C       FALSE 
4 D        TRUE

[1] A B C D
Levels: A B C D

[1] B
Levels: A B C D

[1] A B C D
Levels: A B C D

subject result
2 B       TRUE

subject result
1 A        TRUE 
2 B        TRUE 
3 C       FALSE

## データフレームの並べ替え

In [65]:
df<-data.frame(
    subject=c("Takeda", "Imagawa", "Hojo"),
    result=c(1582, 1569, 1590)
)
df
df[order(df$result),] #昇順
df[order(df$result, decreasing=TRUE),] #降順

subject result
1 Takeda  1582  
2 Imagawa 1569  
3 Hojo    1590

subject result
2 Imagawa 1569  
1 Takeda  1582  
3 Hojo    1590

subject result
3 Hojo    1590  
1 Takeda  1582  
2 Imagawa 1569

---
# 配列
配列は3次元以上のデータを扱うことができます．


## 配列の生成

In [72]:
a<-array(1:8, dim=c(2, 4))
a
a<-array(1:27, dim=c(3,3,3))
a

[,1] [,2] [,3] [,4]
[1,] 1    3    5    7   
[2,] 2    4    6    8

, , 1

     [,1] [,2] [,3]
[1,]    1    4    7
[2,]    2    5    8
[3,]    3    6    9

, , 2

     [,1] [,2] [,3]
[1,]   10   13   16
[2,]   11   14   17
[3,]   12   15   18

, , 3

     [,1] [,2] [,3]
[1,]   19   22   25
[2,]   20   23   26
[3,]   21   24   27

## 配列の参照

In [92]:
a<-array(1:27, dim=c(3,3,3))
a[3,3,3]
a[,1,1]
a[2,,]
a[6:15]

[1] 27

[1] 1 2 3

[,1] [,2] [,3]
[1,] 2    11   20  
[2,] 5    14   23  
[3,] 8    17   26

[1]  6  7  8  9 10 11 12 13 14 15

---
# リスト
リストはベクトルや配列と異なり複数種のオブジェクトをひとつにまとめることが可能です．
リストの中にリストを入れることもできます．

## リストの作成

In [106]:
a<-list(c(6,4,2), 1, list(2, "LIST IN LIST", list(3, "LIST IN LIST IN LIST", "入れ子にもできる")))
a

[[1]]
[1] 6 4 2

[[2]]
[1] 1

[[3]]
[[3]][[1]]
[1] 2

[[3]][[2]]
[1] "LIST IN LIST"

[[3]][[3]]
[[3]][[3]][[1]]
[1] 3

[[3]][[3]][[2]]
[1] "LIST IN LIST IN LIST"

[[3]][[3]][[3]]
[1] "入れ子にもできる"

## リストの参照

In [133]:
a<-list("A", 1, list("B", 2, list("C", 3, 4)))
a
a[1] #リストの1番目を参照（この場合インデックスがつく）
a[[1]] #リストの1番目の要素をインデックスなしで参照
a[[3]][[3]][[3]] #入れ子状態になったリストの要素を参照

[[1]]
[1] "A"

[[2]]
[1] 1

[[3]]
[[3]][[1]]
[1] "B"

[[3]][[2]]
[1] 2

[[3]][[3]]
[[3]][[3]][[1]]
[1] "C"

[[3]][[3]][[2]]
[1] 3

[[3]][[3]][[3]]
[1] 4

[[1]]
[1] "A"

[1] "A"

[1] 4

## リストの要素に名前をつける

In [139]:
#初期化時に名前をつける場合
a<-list(
    name=c("tanaka", "suzuki", "yamada"),
    value=120
)
a
a$name
a$value

#names関数を使う場合
names(a)<-c("lastname","test")
a
a$lastname
a$test

$name
[1] "tanaka" "suzuki" "yamada"

$value
[1] 120

[1] "tanaka" "suzuki" "yamada"

[1] 120

$lastname
[1] "tanaka" "suzuki" "yamada"

$test
[1] 120

[1] "tanaka" "suzuki" "yamada"

[1] 120

---
# Rの数学基本関数
## 三角関数

In [ ]:
pi #円周率

In [ ]:
sin(pi/2) #サイン

In [ ]:
cos(180) #コサイン

In [ ]:
tan(pi) #タンジェント

In [ ]:
atan(pi/2) #アークタンジェント

In [ ]:
sinh(pi) #ハイパボリックサイン

## 対数

In [ ]:
exp(1) #ネイピア数

In [ ]:
#底を指定しないと自然対数になる
log(10)
log(exp(1))
log(exp(2))

In [ ]:
#底を指定する
log(10, base=10)
log(exp(1), base=10)

In [ ]:
4^(1/2)

## 累乗根

In [ ]:
sqrt(4) #平方根
4^(1/2) #平方根
27^(1/3) #3乗根

## その他関数

In [ ]:
abs(-50) #絶対値

In [ ]:
trunc(pi) #整数部分

In [ ]:
#小数点下n桁の四捨五入
round(pi)
round(pi,1)
round(pi, 2)
round(pi, 3)
round(pi,-1)

In [ ]:
floor(2.1) #小数点切り下げ
ceiling(2.1) #小数点切り上げ

In [ ]:
#有効数字n桁
signif(100.6578,2)
signif(100.6578,3)
signif(100.6578,4)
signif(100.6578,5)

---
# 制御構文
## 条件分岐
### if，else文

In [ ]:
a<-2
if(a==1){
    print("1")
}else if(a==2){
    print("2") #実行
}else{
    print("3")
}

### switch文

In [ ]:
a<-2
switch(a,
    "1" = print("1です"),
    "2" = print("2です"), #実行
    "3" = print("3です"),
    print("1,2,3のどれでもないです") #どの条件にも当てはまらないときに実行
)

### ifelse文
C言語等の三項演算子のような処理を書くのに使います．

```
ifelse(条件式, TRUEのときの返り値, FALSEのときの返り値)
```

In [ ]:
a<-1
x<-100
y<-200

b<-ifelse(a==1, x, y)
c<-ifelse(a==2, x, y)
b
c

### 比較演算子
基本的に他言語と同じです．

In [ ]:
a <- 10

a == 10 #等しい
a != 10 #等しくない
a >  9  #～より大きい
a >= 10 #～以上
a <  11 #～未満
a <= 10 #～以下

### 論理演算子

In [ ]:
a<-T
b<-F
c<-T
x<-10
y<-20

a & b #論理積
a | b #論理和

x == 10 & y == 20 #条件式の比較

## 繰り返し
### for文

In [14]:
vec<-c()
for (i in 1:10) {
    vec<-append(vec, i)
}
print(vec)

for (i in vec) {
    print(i)
}

 [1]  1  2  3  4  5  6  7  8  9 10
[1] 1
[1] 2
[1] 3
[1] 4
[1] 5
[1] 6
[1] 7
[1] 8
[1] 9
[1] 10


## while文

In [15]:
x <- 0
while (x < 10) {
    x<-x+1
}
x
x <- 0
while (x <=10) {
    x<-x+1
}
x

[1] 10

[1] 11

## repeat文

In [17]:
x <- 0
repeat {  #breakになるまで繰り返し
    if (x <= 5) x <- x+1
    else  break
}
x

[1] 6

---
# 関数定義
参考: http://cse.naro.affrc.go.jp/takezawa/r-tips/r/31.html

In [1]:
getDouble <- function(x) {
    return(x*2)
}
getDouble(4)

[1] 8